"""expand post

Revision ID: 8725469afee5
Revises: 263a2f948946
Create Date: 2022-08-28 11:40:11.476053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8725469afee5"
down_revision = "263a2f948946"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("handle", sa.String(), nullable=True))
    op.add_column("post", sa.Column("post_ts", sa.DateTime(), nullable=True))
    op.add_column("post", sa.Column("post_update_ts", sa.DateTime(), nullable=True))
    op.add_column("post", sa.Column("hidden", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_post_handle"), "post", ["handle"], unique=False)
    op.create_index(op.f("ix_post_post_ts"), "post", ["post_ts"], unique=False)
    op.create_index(
        op.f("ix_post_post_update_ts"), "post", ["post_update_ts"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_post_update_ts"), table_name="post")
    op.drop_index(op.f("ix_post_post_ts"), table_name="post")
    op.drop_index(op.f("ix_post_handle"), table_name="post")
    op.drop_column("post", "hidden")
    op.drop_column("post", "post_update_ts")
    op.drop_column("post", "post_ts")
    op.drop_column("post", "handle")
    # ### end Alembic commands ###
