"""add summary field for posts

Revision ID: 9ac20ea067ab
Revises: 72d221a62575
Create Date: 2024-03-06 08:36:23.617796

"""
from alembic import op
import sqlalchemy as sa
from markupsafe import Markup
from app.models import Post


# revision identifiers, used by Alembic.
revision = '9ac20ea067ab'
down_revision = '72d221a62575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        # batch_op.drop_column('summary')
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_summary'), ['summary'], unique=False)


    # ### end Alembic commands ###    # Update existing posts with summary
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    try:
        posts = session.query(Post).all()
        for post in posts:
            try:
                first_paragraph = post.content.split("\n")[1]
                first_paragraph = first_paragraph.replace("<p>","")
                first_paragraph = first_paragraph.replace("</p>","")
                post.summary = first_paragraph
            except IndexError:
                post.summary = None
                continue
        session.commit()
    finally:
        session.close()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_summary'))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
